// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dkyazgdsczgiceertjyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRreWF6Z2RzY3pnaWNlZXJ0anlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MjE5NTMsImV4cCI6MjA1OTQ5Nzk1M30.n3kXrW4KU22HVTvg4Vf8NApCJYBnXiWu9P8wMssST8A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);